name: CI (Flatpak)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Do not cancel in-progress runs if a labeling action took place (other than 'flatpak'). Otherwise, adding irrelevant
  # labels causes existing runs to be canceled and a new (identical) run to be started.
  cancel-in-progress: ${{ (github.event.action != 'labeled' && github.event.action != 'unlabeled') || github.event.label.name == 'flatpak' }}

jobs:
  CI-Flatpak:
    name: Flatpak ${{ matrix.arch }}

    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64']
        runner_labels: ['["blacksmith-16vcpu-ubuntu-2404"]']

        include:
          - arch: 'aarch64'
            runner_labels: '["blacksmith-16vcpu-ubuntu-2404-arm"]'

    secrets: inherit
    uses: ./.github/workflows/flatpak-template.yml
    with:
      arch: ${{ matrix.arch }}
      runner_labels: ${{ matrix.runner_labels }}
